### ISSUE TITLE
Continueing will break the loop.index

### ISSUE THREAD

**Issue by sudo-plz** [marionnewlevant/craft-mnbreakandcontinue#1]
The index will stay the same after an continue instead of upped.

**Comment by marionnewlevant** [comment]
So it does! Thank you for pointing this out. Fixed in latest (1.1.1) release

**Comment by sudo-plz** [comment]
Yet, its still broken in the craft 3 branch.

**Comment by marionnewlevant** [comment]
Fixed in craft 3 now as well. If you need the craft3 version you should use this plugin. If you just need break and continue in craft2, you might prefer [twig perversion](https://github.com/marionnewlevant/craft-twig_perversion)
